# Generated by Django 3.1.5 on 2021-07-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('usuario', 'Usuário'), ('profissional', 'Profissional')], max_length=13, verbose_name='Perfil'),
        ),
    ]
