# Generated by Django 3.1.5 on 2021-07-27 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20210727_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Usuário ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Usuário admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('profissional', 'Profissional'), ('usuario', 'Usuário')], max_length=13, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Membro da equipe'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('photograph', models.ImageField(upload_to='', verbose_name='Foto')),
                ('doc_id', models.CharField(max_length=20, verbose_name='Documento de identidade')),
                ('street', models.CharField(max_length=30, verbose_name='Rua/av.')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('compl', models.CharField(blank=True, max_length=30, verbose_name='Complemento')),
                ('neighbor', models.CharField(max_length=30, verbose_name='Bairro')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
                ('category', models.CharField(blank=True, choices=[('enventos', 'enventos'), ('entretenimento', 'entretenimento'), ('automotivo', 'automotivo'), ('serviços elétricos', 'serviços elétricos'), ('professores', 'professores'), ('entregadores', 'entregadores'), ('predeiros', 'predeiros'), ('motorista', 'motorista'), ('outros', 'outros')], max_length=50, verbose_name='Categoria')),
                ('curriculum', models.TextField(blank=True, null=True)),
                ('terms', models.BooleanField(default=False, verbose_name='Aceito os Termos')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data do cadastro')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
