# Generated by Django 3.1.5 on 2021-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20210727_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_profile',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
