# Generated by Django 3.1.5 on 2021-07-28 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20210728_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photograph',
            field=models.ImageField(blank=True, upload_to='usuario', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('usuario', 'Usuário'), ('profissional', 'Profissional')], max_length=13, verbose_name='Perfil'),
        ),
    ]
