# Generated by Django 3.1.5 on 2021-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20210728_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photograph',
            field=models.ImageField(upload_to='usuario/%Y/%m/%d', verbose_name='Foto'),
        ),
    ]
